# Generated by Django 5.0.6 on 2024-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='allow_embed',
            field=models.BooleanField(default=True),
        ),
    ]
