# Generated by Django 5.0.6 on 2024-11-05 14:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0002_trivia_allow_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='reset_time',
            field=models.TimeField(default=datetime.datetime(2024, 11, 5, 14, 49, 33, 95208)),
        ),
        migrations.CreateModel(
            name='TriviaGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('last_win_date', models.DateTimeField(blank=True, null=True)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailytrivia.trivia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
