# Generated by Django 5.0.6 on 2024-11-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0005_rename_last_attempt_date_triviagamerecord_last_attempt_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triviagamerecord',
            old_name='last_win_date',
            new_name='last_win_datetime',
        ),
        migrations.AlterUniqueTogether(
            name='triviagamerecord',
            unique_together={('user', 'trivia')},
        ),
    ]
