# Generated by Django 5.0.6 on 2024-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0006_rename_last_win_date_triviagamerecord_last_win_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
