# Generated by Django 5.0.6 on 2024-11-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0007_trivia_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='image',
            field=models.URLField(default='https://png.pngtree.com/png-clipart/20210905/original/pngtree-trivia-poster-png-image_6706386.jpg', max_length=500),
        ),
    ]
