# Generated by Django 5.0.6 on 2024-11-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0008_trivia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviagamerecord',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
