# Generated by Django 5.0.6 on 2024-11-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0009_triviagamerecord_streak_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviagamerecord',
            name='streak_count',
        ),
    ]
