# Generated by Django 5.0.6 on 2024-11-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0012_usertriviadates_delete_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertriviadates',
            name='highest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
