# Generated by Django 5.0.6 on 2024-11-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrivia', '0013_usertriviadates_highest_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertriviadates',
            name='highest_streak',
        ),
    ]
